Fix NoMethodError at Orthoses::ActiveRecord::Scope middleware
When passing callable object to scope

e.g. using Query Object Pattern
c.f. https://takaokouji.github.io/output/query-object/

```ruby
class FilterByStatusQuery
  private attr_reader :relation, :options

  def self.call(*args)
    new(*args).send(:query)
  end

  def initialize(*args)
    @options = args.extract_options!
    @relation = Blog
  end

  private

  def query
    relation.where(status: options[:status])
  end
end

class Blog < ApplicationRecord
  scope :by_status, FilterByStatusQuery
end
```

Orthoses raises NoMethodError because Class doesn't respond to parameters

```
$ bin/rails orthoses:rails

...

Caused by:
NoMethodError: undefined method `parameters' for FilterByStatusQuery:Class (NoMethodError)

          definition = "#{name}: #{parameters_to_type(body.parameters)} -> #{base_name}::ActiveRecord_Relation"
                                                          ^^^^^^^^^^^
```

So captured argument body is not Proc and callable, we should use Method#parameters